export function teamColors(team) {
  return team === "A"
    ? {
        bg: "bg-pastel-sky/60 dark:bg-accent-sky/15",
        border: "border-accent-sky/50",
        borderFaint: "border-accent-sky/25",
        dot: "bg-accent-sky",
        iconBg: "bg-pastel-sky dark:bg-accent-sky/20",
        iconText: "text-accent-sky",
        gradientFrom: "from-pastel-sky/80 dark:from-accent-sky/10",
        avatarBg: "bg-accent-sky",
        highlight: "bg-pastel-sky dark:bg-accent-sky/20",
        label: "Alpha",
        pillBg: "bg-pastel-sky dark:bg-accent-sky/20",
        pillBorder: "border-accent-sky/30",
        pillText: "text-accent-sky",
        activeScoreBg: "bg-pastel-sky/80 border-accent-sky/40 dark:bg-accent-sky/15",
        inactiveScoreBg: "bg-muted-bright/30 border-foreground/10",
        youText: "text-accent-sky",
        timerBar: "from-accent-sky to-accent-sky/70",
      }
    : {
        bg: "bg-pastel-peach/60 dark:bg-primary/15",
        border: "border-primary/50",
        borderFaint: "border-primary/25",
        dot: "bg-primary",
        iconBg: "bg-pastel-peach dark:bg-primary/20",
        iconText: "text-primary",
        gradientFrom: "from-pastel-peach/80 dark:from-primary/10",
        avatarBg: "bg-primary",
        highlight: "bg-pastel-peach dark:bg-primary/20",
        label: "Beta",
        pillBg: "bg-pastel-peach dark:bg-primary/20",
        pillBorder: "border-primary/30",
        pillText: "text-primary",
        activeScoreBg: "bg-pastel-peach/80 border-primary/40 dark:bg-primary/15",
        inactiveScoreBg: "bg-muted-bright/30 border-foreground/10",
        youText: "text-primary",
        timerBar: "from-primary to-primary-light",
      };
}
